apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: app-reader
  namespace: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-reader
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-reader
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app.kubernetes.io/created-by: Fractal
        prometheus.io/scrape: "true"
        app: app-reader
    spec:
      serviceAccountName: app-reader
      containers:
        - name: app-reader
          image: $IMAGE_READER
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: $KAFKA_BOOTSTRAP_SERVERS
            - name: ENVIRONMENT
              value: $ENVIRONMENT