apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: app-writer
  namespace: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-writer
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-writer
  template:
    metadata:
      labels:
        app: app-writer
    spec:
      serviceAccountName: app-writer
      containers:
        - name: app-writer
          image: $IMAGE_WRITER
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: $KAFKA_BOOTSTRAP_SERVERS
            - name: ENVIRONMENT
              value: $ENVIRONMENT