/*
 * This source file was generated by the Gradle 'init' task
 */
package cloud.fractal.samples.automotive.environment;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appLoads() {
  }
}
