/*
 * This source file was generated by the Gradle 'init' task
 */
package cloud.fractal.samples.automotive.application.writer;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@EnableJpaRepositories
@SpringBootApplication
public class WriterApp {
  public static void main(String[] args) {
    SpringApplication.run(WriterApp.class, args);
  }
}
